### ISSUE TITLE
Dividing by 100 for team desires config object in frontend...

### ISSUE THREAD

**Issue by SpellBreakerZA** [301-Redirection/301-Project#186]
This needs to be double checked again. I entered # enemies alive equal to 2 and then clicked the plus to create an and condition and then it became 0.02...

**Comment by vector67** [comment]
I think this has been fixed by #205

**Comment by russelldutton** [comment]
I do apologize for the confusion. This has since been updated by #205 to do the conversions in the express Lua code generation.
I found that doing the conversions in Angular messed up how they were stored and retrieved in an object. Because the data value in the object is bound to an element on the screen, every time you divide by 100 in the service it updates the value on the frontend, which is why the slider kept jumping back to 0.

**Comment by vector67** [comment]
Fixed by #205
